---
# tasks file for tcpdump

- name: print information about the next task
  ansible.builtin.debug:
    msg:
      - "next task: start tcpdump"
      - "capture time is {{ capture_time }} seconds"

- name: start tcpdump
  ansible.builtin.command:
    cmd: tcpdump -i {{ capture_interface }} -G {{ capture_time }} -W 1 -nn -s0 -v -w {{ capture_src }}
  become: true
  register: output
  changed_when: true
  notify: remove tcpdump.pcap from target

- name: fetch tcpdump.pcap from remote server
  ansible.builtin.fetch:
    src: "{{ capture_src }}"
    dest: "{{ capture_dest }}"
    flat: true
  when: ansible_connection != 'local'
