---
# tasks file for serial_terminal

- name: Get usbserial
  ansible.builtin.find:
    paths: /dev
    patterns: tty.usb*
    file_type: any
  register: output

- name: Run this command
  ansible.builtin.debug:
    msg: screen {{ output.files[0].path }}
